# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = ImageProcessing
DESTDIR = ../x64/Debug
CONFIG += debug
LIBS += -lgdal_i
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
LIBS += -lgdal